export function wordCard({ id, word, definition, synonyms }, escapeHtml) {
  return `<article class="word-card group rounded-xl border border-slate-200 p-4 transition hover:border-indigo-300 hover:shadow-sm"><div class="flex items-start justify-between gap-4"><div class="min-w-0"><h3 class="truncate text-lg font-bold text-slate-900">${escapeHtml(word)}</h3><p class="mt-1 text-xs font-semibold text-indigo-600">${escapeHtml(synonyms.join(", "))}</p></div><div class="flex shrink-0 gap-1 opacity-0 transition group-hover:opacity-100"><button class="rounded-md p-2 text-slate-400 hover:bg-slate-100 hover:text-indigo-600" data-action="info" data-id="${id}" aria-label="View details for ${escapeHtml(word)}" title="View details">ⓘ</button><button class="rounded-md p-2 text-slate-400 hover:bg-slate-100 hover:text-indigo-600" data-action="edit" data-id="${id}" aria-label="Edit ${escapeHtml(word)}" title="Edit">✎</button><button class="rounded-md p-2 text-slate-400 hover:bg-red-50 hover:text-red-500" data-action="delete" data-id="${id}" aria-label="Delete ${escapeHtml(word)}" title="Delete">×</button></div></div><p class="mt-3 text-sm leading-6 text-slate-500">${escapeHtml(definition)}</p></article>`;
}

export function wordDialog() {
  return `<dialog id="word-dialog" class="w-[min(440px,calc(100%-2rem))] rounded-2xl border-0 bg-white p-0 shadow-2xl backdrop:bg-slate-950/40"><form id="word-form" class="p-6 sm:p-8"><div class="mb-7 flex items-start justify-between"><div><p class="mb-1 text-xs font-bold uppercase tracking-[0.16em] text-indigo-600">WORD ENTRY</p><h2 class="text-2xl font-bold text-slate-900" id="dialog-title">Add new word</h2></div><button class="rounded-lg p-2 text-xl leading-none text-slate-400 hover:bg-slate-100" type="button" data-action="close-dialog" aria-label="Close">×</button></div><input id="word-id" type="hidden"><label class="mb-4 block text-xs font-bold uppercase tracking-wider text-slate-500">Word<input class="mt-2 w-full rounded-lg border border-slate-200 px-3.5 py-3 text-sm font-normal normal-case tracking-normal text-slate-800 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" id="word-input" required placeholder="e.g. Serendipity"></label><label class="mb-4 block text-xs font-bold uppercase tracking-wider text-slate-500">Definition<textarea class="mt-2 min-h-24 w-full resize-y rounded-lg border border-slate-200 px-3.5 py-3 text-sm font-normal normal-case tracking-normal text-slate-800 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" id="definition-input" required placeholder="What does it mean?"></textarea></label><fieldset class="mb-6"><legend class="text-xs font-bold uppercase tracking-wider text-slate-500">Synonyms <span class="font-normal normal-case tracking-normal text-slate-400">Press Tab for another</span></legend><div class="mt-2 space-y-2" id="synonym-fields"></div></fieldset><button class="flex w-full items-center justify-between rounded-lg bg-indigo-600 px-4 py-3 text-sm font-bold text-white transition hover:bg-indigo-700" type="submit">Save word <span class="text-lg">→</span></button></form></dialog>`;
}

export function wordDetailDialog() {
  return `<dialog id="word-detail-dialog" class="w-[min(440px,calc(100%-2rem))] rounded-2xl border-0 bg-white p-0 shadow-2xl backdrop:bg-slate-950/40"><div class="p-6 sm:p-8"><div class="mb-7 flex items-start justify-between"><div><p class="mb-1 text-xs font-bold uppercase tracking-[0.16em] text-indigo-600">WORD DETAILS</p><h2 class="text-2xl font-bold text-slate-900" id="detail-word"></h2></div><button class="rounded-lg p-2 text-xl leading-none text-slate-400 hover:bg-slate-100" type="button" data-action="close-detail" aria-label="Close">×</button></div><p class="text-sm leading-7 text-slate-600" id="detail-definition"></p><div class="mt-6"><p class="text-xs font-bold uppercase tracking-wider text-slate-500">Synonyms</p><p class="mt-2 text-sm font-semibold text-indigo-600" id="detail-synonyms"></p></div></div></dialog>`;
}

export function deleteDialog() {
  return `<dialog id="delete-dialog" class="w-[min(400px,calc(100%-2rem))] rounded-2xl border-0 bg-white p-0 shadow-2xl backdrop:bg-slate-950/40"><div class="p-6 sm:p-8"><div class="mb-6 flex items-start justify-between"><div><p class="mb-1 text-xs font-bold uppercase tracking-[0.16em] text-red-500">DELETE WORD</p><h2 class="text-2xl font-bold text-slate-900">Are you sure?</h2></div><button class="rounded-lg p-2 text-xl leading-none text-slate-400 hover:bg-slate-100" type="button" data-action="close-delete" aria-label="Close">×</button></div><p class="text-sm leading-6 text-slate-500">This word will be removed from your library.</p><div class="mt-7 flex justify-end gap-3"><button class="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50" type="button" data-action="close-delete">Cancel</button><button class="rounded-lg bg-red-500 px-4 py-2.5 text-sm font-bold text-white hover:bg-red-600" type="button" data-action="confirm-delete">Delete</button></div></div></dialog>`;
}
